
name: bayestracking
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: L-CAS Bayestracking
description: |
  This build a bayestracking library

grade: devel
confinement: devmode

parts:
  bayestracking:
    source: https://github.com/LCAS/bayestracking.git
    source-branch: master
    plugin: catkin
    rosdistro: kinetic
    source-space: .
    catkin-packages: [bayestracking]
